import { raleway } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import "../(client)/globals.css";
import "./dashboard.css";

import SideNav from "./_components/sidenav/sidenav";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(`${raleway.className} w-full flex`)}>
        <SideNav />
        <div className="bg-[#FDFDFD] h-screen rounded-[8px] w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
