import "../../globals.css";
import { cn } from "@/lib/utils";
import { raleway } from "@/lib/fonts";
import Header from "../../_component/Header";
import Footer from "../../_component/Footer";
import { CartProvider } from "@/context/cartContext";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Checkout page",
  description: "Generated by create next app",
};

export default function OrderLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={cn(`${raleway.className}`)}>
          <Header />
          {children}
          <Footer />
          <Toaster />
        </body>
      </CartProvider>
    </html>
  );
}
