import "../../globals.css";
import { cn } from "@/lib/utils";
import { raleway } from "@/lib/fonts";
import Header from "../../_component/Header";
import Footer from "../../_component/Footer";

export const metadata = {
  title: "Checkout page",
  description: "Generated by create next app",
};

export default function CheckoutLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(`${raleway.className}`)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
