import "../globals.css";
import { cn } from "@/lib/utils";
import { raleway } from "@/lib/fonts";
import { CartProvider } from "@/context/cartContext";

export const metadata = {
  title: "Checkout page",
  description: "Generated by create next app",
};

export default function CheckoutLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(`${raleway.className}`)}>{children}</body>
    </html>
  );
}
